"use strict";

const HOW_TO_KEY = "bellPerformanceHowToSeenV7";
const howToSlides = [
  {kicker:"Bell Performance",title:"A coach-led cockpit, not a generic app",body:"Bell Performance is designed to feel like a knowledgeable private coach. Each screen has a job, and the visual language stays consistent from the dashboard to workouts, progress, and settings.",bullets:["Dark cinematic visuals keep the app premium without feeling noisy.","Gold highlights direct attention to the next important action.","Home is command center; the other screens support execution and review."],image:"./assets/artwork/strength/custom-strength-shadows.jpg?v=8600",visual:"Premium Home Experience",detail:"Commercial polish with a coaching mindset.",screen:"home",target:".brand-header",theme:"strength"},
  {kicker:"Home",title:"Start every day on the dashboard",body:"The dashboard brings together your quote, readiness, mission, support work, weekly rhythm, coach briefing, progress, and standards. It should answer what to do next within a few seconds.",bullets:["Read the page top to bottom.","Use the streak and current block week for context.","Coach Briefing explains the current phase rather than leaving programming mysterious."],image:"./assets/artwork/engine/custom-ridge-runner.jpg?v=8600",visual:"Command Center",detail:"Assess. Execute. Recover. Repeat.",screen:"home",target:".dashboard-greeting",theme:"engine"},
  {kicker:"Readiness",title:"Check in fast with slider-based readiness",body:"Daily readiness is intentionally quick. Sleep uses 15-minute increments, and every other slider moves in the same direction: 1 is worst, 5 is best. The score helps the app scale the day intelligently.",metrics:[["Sleep","15-min increments"],["Quality","1 = poor, 5 = excellent"],["Energy","1 = depleted, 5 = energized"],["Recovery","1 = very sore, 5 = fresh"],["Motivation","1 = low, 5 = high"]],image:"./assets/artwork/engine/forest-trail.jpg?v=8600",visual:"Fast Daily Check-In",detail:"Simple input. Smarter adjustment.",screen:"home",target:"#premiumReadinessCard",panelPosition:"left",theme:"engine"},
  {kicker:"Mission",title:"The day’s training lives in one clean module",body:"Today’s Mission keeps Strength, Engine, and Optional Core together so two-a-day programming still feels organized. Selectors for gym location and engine mode live right inside the rows where they matter.",bullets:["The completion ring tracks only prescribed work.","Optional Core and support stay visible without confusing completion.","Start, Resume, and Completed states update automatically."],image:"./assets/artwork/strength/custom-heavy-deadlift.jpg?v=8600",visual:"Today’s Mission",detail:"One unified training picture.",screen:"home",target:".premium-mission-card",theme:"strength"},
  {kicker:"Weekly rhythm",title:"Use the weekly strip to preview the plan",body:"The weekly schedule mirrors the dashboard’s icon treatment so it feels like part of the same system. Strength and Engine days use the same premium buttons, and two-session days show both at a glance.",bullets:["Tap any day to preview it on the dashboard.","Completed, current, and selected states all stay visible.","Open Weekly Plan when you want the longer form schedule."],image:"./assets/artwork/engine/custom-sandbag-trek.jpg?v=8600",visual:"Weekly Rhythm",detail:"Small control, high clarity.",screen:"home",target:".premium-week-card",theme:"engine"},
  {kicker:"Training",title:"The Training Library supports the mission",body:"Home is the fastest route to today’s work, but the Training tab remains your full library. Use it to review the rotation, study the week, or launch a prescribed session directly.",bullets:["Strength, Engine, and optional work stay organized by purpose.","Use the library when you want more context around the rotation.","Exercise substitutions still honor your current equipment and location."],image:"./assets/artwork/strength/custom-sled-push.jpg?v=8600",visual:"Training Library",detail:"Browse the system without getting lost in it.",screen:"workouts",target:"#workouts .section-heading",theme:"strength"},
  {kicker:"Workout screen",title:"Log real training, not just completion",body:"Inside the workout screen, the hero, exercise cards, and controls are built to look sharp while staying practical. Record what you truly did so Bell Performance can guide the next prescription more accurately.",feedback:["Weight used","Reps completed","RPE / effort","Pain or technique notes"],image:"./assets/artwork/strength/custom-heavy-deadlift.jpg?v=8600",visual:"Workout Execution",detail:"Good coaching depends on honest training data.",screen:"workouts",target:"#workoutLibrary",theme:"strength"},
  {kicker:"Plan",title:"Weekly Plan shows the full training architecture",body:"The Plan screen gives you the structured week view behind the dashboard. It helps you understand how the current block is laid out and how sessions fit together over time.",bullets:["Use it to preview tomorrow or next week.","See how Strength and Engine are arranged across the week.","The page is for planning and confidence, not just for checking boxes."],image:"./assets/artwork/engine/custom-ridge-runner.jpg?v=8600",visual:"Weekly Plan",detail:"Understand the architecture behind the day.",screen:"plan",target:"#planList",theme:"engine"},
  {kicker:"History",title:"Progress should feel coached, not random",body:"Performance Review and Training History help you see whether the block is working. Use them to assess consistency, training volume, engine progress, and the bigger direction of the mission.",bullets:["Review trends, not only one-off good days.","Milestones help reinforce momentum over time.","History builds trust that the program is truly progressing."],image:"./assets/artwork/engine/hill-country.jpg?v=8600",visual:"Performance Review",detail:"Track the story, not just the score.",screen:"history",target:"#history .section-title",theme:"engine"},
  {kicker:"More",title:"Settings keeps the system adaptable",body:"Mission editing, equipment, help, and preferences live under More. When life changes, this is where Bell Performance stays flexible without losing the logic of the larger plan.",bullets:["Update equipment when your training environment changes.","Adjust the mission when your priority or event changes.","Replay the tour from Help anytime."],image:"./assets/artwork/strength/upper-body.jpg?v=8600",visual:"Settings & Support",detail:"Adapt the app without starting over.",screen:"more",target:"#more .settings-section-heading",theme:"system"},
  {kicker:"Ready to train",title:"Use the app like a premium coaching system",body:"The daily rhythm is simple: check in, review the mission, train honestly, recover intentionally, and review progress over time. That is what keeps Bell Performance feeling like a real coaching product instead of a generic workout app.",bullets:["Start on Home each day.","Use Training and Plan for context and execution.","Use History and More to review, adjust, and keep the system aligned with real life."],image:"./assets/artwork/strength/custom-strength-shadows.jpg?v=8600",visual:"You’re Ready",detail:"The full tour can always be replayed from Help.",screen:"home",target:".brand-header",theme:"strength"}
];
let howToIndex=0, howToTimer=null, resumeFirstFlightAfterTour=false, activeTourTarget=null, howToReturnScreen='home';
function clearHowToTarget(){if(activeTourTarget){activeTourTarget.classList.remove('tour-highlight');activeTourTarget=null;}document.body.classList.remove('tour-active');const modal=document.getElementById('howToModal');if(modal)modal.classList.remove('tour-panel-left');}
function activeScreenName(){return document.querySelector('.screen.active')?.id || 'home';}
function applyHowToTarget(slide){ clearHowToTarget(); const modal=document.getElementById('howToModal'); if(modal&&slide.panelPosition==='left')modal.classList.add('tour-panel-left'); if(slide.screen&&typeof showScreen==='function')showScreen(slide.screen); const target=slide.target?document.querySelector(slide.target):null; if(!target)return; activeTourTarget=target; target.classList.add('tour-highlight'); document.body.classList.add('tour-active'); window.setTimeout(()=>target.scrollIntoView({behavior:'smooth',block:'center'}),80); }
function openHowToGuide(startIndex=0,options={}){ resumeFirstFlightAfterTour=Boolean(options.resumeFirstFlight); howToReturnScreen=activeScreenName(); howToIndex=Math.max(0,Math.min(howToSlides.length-1,Number(startIndex)||0)); document.getElementById('howToModal')?.classList.remove('hidden'); document.body.classList.add('modal-open'); renderHowToSlide(); }
function launchFirstFlightTour(){openHowToGuide(0,{resumeFirstFlight:true});}
function closeHowToGuide(){ stopHowToAutoplay(); clearHowToTarget(); document.getElementById('howToModal')?.classList.add('hidden'); document.body.classList.remove('modal-open'); localStorage.setItem(HOW_TO_KEY,'1'); if(typeof showScreen==='function')showScreen(resumeFirstFlightAfterTour ? 'home' : howToReturnScreen); if(resumeFirstFlightAfterTour){ resumeFirstFlightAfterTour=false; data.settings.firstFlightTourComplete=true; data.settings.firstFlightStage='configure'; saveData({render:false}); window.setTimeout(()=>openFirstFlight(2),180); } }
function howToFallbackImage(theme){return theme==='strength'?'./assets/strength-classic.jpg?v=8600':'./assets/engine-mountain-trail.jpg?v=8600';}
function renderHowToSlide(){ const slide=howToSlides[howToIndex]; applyHowToTarget(slide); const extras=slide.metrics?`<div class="guide-metric-grid">${slide.metrics.map(x=>`<div class="guide-metric"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}</div>`:slide.feedback?`<div class="guide-feedback">${slide.feedback.map(x=>`<span>${x}</span>`).join('')}</div>`:slide.bullets?`<ul>${slide.bullets.map(x=>`<li>${x}</li>`).join('')}</ul>`:''; const tags=(slide.bullets||[]).slice(0,3).map(x=>x.replace(/^Use\s+/,'').replace(/^Bell Performance\s+/,'')).map(x=>`<i>${x.split('.')[0]}</i>`).join(''); document.getElementById('howToTitle').textContent=slide.title; document.getElementById('howToSlide').innerHTML=`<div class="how-to-slide-copy"><div class="how-to-kicker">${slide.kicker}</div><h3>${slide.title}</h3><p>${slide.body}</p>${extras}</div><div class="how-to-visual" data-theme="${slide.theme||'system'}"><img src="${slide.image}" alt="" onerror="this.onerror=null;this.src='${howToFallbackImage(slide.theme)}';"><div class="how-to-visual-content"><div class="how-to-visual-badge">Bell Performance Tour</div><strong>${slide.visual}</strong><span>${slide.detail}</span>${tags?`<div class="how-to-tags">${tags}</div>`:''}</div></div>`; document.getElementById('howToProgress').style.width=`${((howToIndex+1)/howToSlides.length)*100}%`; document.getElementById('howToBack').disabled=howToIndex===0; document.getElementById('howToNext').textContent=howToIndex===howToSlides.length-1?(resumeFirstFlightAfterTour?'Continue First Flight':'Finish'):'Next'; document.getElementById('howToDots').innerHTML=howToSlides.map((_,i)=>`<button class="${i===howToIndex?'active':''}" aria-label="Go to slide ${i+1}" onclick="goToHowToSlide(${i})"></button>`).join(''); }
function nextHowToSlide(){ if(howToIndex>=howToSlides.length-1){closeHowToGuide();return;} howToIndex++; renderHowToSlide(); }
function previousHowToSlide(){ if(howToIndex>0){ howToIndex--; renderHowToSlide(); } }
function goToHowToSlide(i){ howToIndex=i; renderHowToSlide(); }
function toggleHowToAutoplay(){ howToTimer?stopHowToAutoplay():startHowToAutoplay(); }
function startHowToAutoplay(){ document.getElementById('howToAutoPlay').textContent='Ⅱ Pause Auto-Advance'; howToTimer=setInterval(()=>{ if(howToIndex===howToSlides.length-1){stopHowToAutoplay();return;} howToIndex++; renderHowToSlide(); },7200); }
function stopHowToAutoplay(){ if(howToTimer)clearInterval(howToTimer); howToTimer=null; const b=document.getElementById('howToAutoPlay'); if(b)b.textContent='▶ Auto-Advance'; }
function hasSeenHowToGuide(){ return localStorage.getItem(HOW_TO_KEY)==='1'; }
function maybeShowHowToGuideAfterProfileSetup(){ if(hasSeenHowToGuide())return; window.setTimeout(()=>openHowToGuide(0),350); }
window.addEventListener('keydown',e=>{ if(document.getElementById('howToModal')?.classList.contains('hidden'))return; if(e.key==='Escape')closeHowToGuide(); if(e.key==='ArrowRight')nextHowToSlide(); if(e.key==='ArrowLeft')previousHowToSlide(); });
