"use strict";

const HOW_TO_KEY = "bellPerformanceHowToSeenV8";
const howToSlides = [
  {kicker:"Bell Performance",title:"Your training command center",body:"Bell Performance connects your Journey, weekly plan, daily readiness, workout execution, recovery, and progress in one coaching system.",bullets:["Gold highlights the next important action.","The dashboard answers what to do today.","Every other screen supports planning, execution, or review."],image:"./assets/artwork/strength/custom-strength-shadows.jpg?v=13720",visual:"Bell Performance",detail:"Assess. Execute. Recover. Repeat.",screen:"home",target:".brand-header",theme:"strength"},
  {kicker:"Daily Check-In",title:"Start with the same 10-second readiness check every day",body:"Choose how you slept, how your body feels, your energy, any pain concern, and the time available. Bell Coach can use that information to adjust today’s prescription; Workout Planner keeps it informational.",metrics:[["Sleep","Poor · Okay · Good"],["Body","Beat Up · Normal · Fresh"],["Energy","Drained · Steady · Fired Up"],["Pain","Flag concerns separately"],["Time","Controls session length"]],image:"./assets/artwork/engine/forest-trail.jpg?v=13720",visual:"10-Second Check-In",detail:"The onboarding check-in and dashboard check-in are now the same system.",screen:"home",target:"#premiumReadinessCard",panelPosition:"left",theme:"engine"},
  {kicker:"Today’s Mission",title:"See the entire training day in one place",body:"Today’s Mission organizes prescribed Strength, Engine, Core, and Recovery work without turning the dashboard into a cluttered workout list.",bullets:["The primary action opens the correct session.","Completion tracks prescribed work only.","Bell Coach explains why today matters."],image:"./assets/artwork/strength/custom-heavy-deadlift.jpg?v=13720",visual:"Today’s Mission",detail:"One clear route into the work.",screen:"home",target:".premium-mission-card",theme:"strength"},
  {kicker:"Bell Coach",title:"Today’s direction must match your Journey",body:"The coach message, training phase, event family, and workout prescription now read from the same compiled mission. A physique athlete should see physique preparation—not tactical fallback language.",bullets:["Continuous development follows the selected objective.","Event preparation follows the selected event type and date.","Readiness changes the day without changing the mission."],image:"./assets/artwork/strength/bodybuilding.jpg?v=13720",visual:"Aligned Coaching",detail:"Identity, Journey, and today’s workout stay connected.",screen:"home",target:".premium-coach-card",theme:"strength"},
  {kicker:"Weekly Rhythm",title:"Preview the plan before life changes it",body:"The weekly strip shows Strength, Engine, Recovery, and completed work at a glance. Open Calendar for the full week and use the schedule tools when availability changes.",bullets:["Tap a day to preview it.","Completed and current states remain visible.","Missed sessions should be handled—not blindly stacked."],image:"./assets/artwork/engine/custom-sandbag-trek.jpg?v=13720",visual:"Weekly Rhythm",detail:"Understand the week before you execute the day.",screen:"home",target:".premium-week-card",theme:"engine"},
  {kicker:"Workouts",title:"Execute and log the real session",body:"Open the workout, review the coach brief, complete the warm-up, log sets and results, and finish with honest feedback. Bell improves only when the recorded work reflects what actually happened.",feedback:["Weight used","Reps completed","RPE and effort","Pain or technique notes"],image:"./assets/artwork/strength/custom-heavy-deadlift.jpg?v=13720",visual:"Workout Execution",detail:"Real training data drives better prescriptions.",screen:"workouts",target:"#workoutLibrary",theme:"strength"},
  {kicker:"Training Library",title:"Use guides when technique or substitutions matter",body:"The Training Library provides exercise context, coaching cues, muscle maps, equipment requirements, and purposeful substitutions. Production guides will expand after the core app is stable.",bullets:["Open guides from the library or workout player.","Substitutions should preserve training intent.","Back Squat is the current production-standard guide."],image:"./assets/library/back-squat-production-guide.png?v=13710",visual:"Exercise Guides",detail:"Learn the movement without leaving the training system.",screen:"workouts",target:"#workouts .section-heading",theme:"strength"},
  {kicker:"Performance",title:"Review trends instead of judging one day",body:"Training History, readiness trends, milestones, and performance reviews show whether the Journey is working over time.",bullets:["Look for repeatable progress.","Use missed-session and recovery patterns as useful data.","Update baselines when verified performance improves."],image:"./assets/artwork/engine/hill-country.jpg?v=13720",visual:"Performance Review",detail:"Track the story, not only the score.",screen:"history",target:"#history .section-title",theme:"engine"},
  {kicker:"Settings",title:"Change the system without wiping your history",body:"Update your athlete profile, mission, schedule, equipment, limitations, coaching behavior, and help resources from Settings.",bullets:["Edit the Journey when the objective or event changes.","Update equipment when the training environment changes.","Replay this tour from Help at any time."],image:"./assets/artwork/strength/upper-body.jpg?v=13720",visual:"Control Center",detail:"Adapt the plan while preserving the work already completed.",screen:"more",target:"#settingsHub",theme:"system"},
  {kicker:"Ready",title:"Begin with today’s Mission",body:"The daily rhythm is simple: check in, understand the direction, execute honestly, recover intentionally, and review the trend. The dashboard is now ready for real-world testing.",bullets:["Start on Dashboard each day.","Use Calendar and Workouts for context and execution.","Report anything confusing, incorrect, or blocked."],image:"./assets/artwork/strength/custom-strength-shadows.jpg?v=13720",visual:"Ready for Testing",detail:"The tour will return you to the dashboard.",screen:"home",target:".brand-header",theme:"strength"}
];
let howToIndex=0, howToTimer=null, firstFlightTourActive=false, activeTourTarget=null, howToReturnScreen="home";
function clearHowToTarget(){if(activeTourTarget){activeTourTarget.classList.remove("tour-highlight");activeTourTarget=null;}document.body.classList.remove("tour-active");const modal=document.getElementById("howToModal");if(modal)modal.classList.remove("tour-panel-left");}
function activeScreenName(){return document.querySelector(".screen.active")?.id||"home";}
function applyHowToTarget(slide){clearHowToTarget();const modal=document.getElementById("howToModal");if(modal&&slide.panelPosition==="left")modal.classList.add("tour-panel-left");if(slide.screen&&typeof showScreen==="function")showScreen(slide.screen);const target=slide.target?document.querySelector(slide.target):null;if(!target)return;activeTourTarget=target;target.classList.add("tour-highlight");document.body.classList.add("tour-active");window.setTimeout(()=>target.scrollIntoView({behavior:"smooth",block:"center"}),80);}
function openHowToGuide(startIndex=0,options={}){firstFlightTourActive=Boolean(options.firstFlight||options.resumeFirstFlight);howToReturnScreen=firstFlightTourActive?"home":activeScreenName();howToIndex=Math.max(0,Math.min(howToSlides.length-1,Number(startIndex)||0));document.getElementById("howToModal")?.classList.remove("hidden");document.body.classList.add("modal-open");renderHowToSlide();}
function launchFirstFlightTour(){openHowToGuide(0,{firstFlight:true});}
function closeHowToGuide(){stopHowToAutoplay();clearHowToTarget();document.getElementById("howToModal")?.classList.add("hidden");document.body.classList.remove("modal-open");localStorage.setItem(HOW_TO_KEY,"1");if(firstFlightTourActive){firstFlightTourActive=false;data.settings.firstFlightTourComplete=true;data.settings.pendingFirstFlightTour=false;data.settings.firstFlightStage="complete";saveData({render:false});if(typeof showScreen==="function")showScreen("home");if(typeof renderApp==="function")renderApp();else if(typeof renderBellCommercialHome==="function")renderBellCommercialHome();window.scrollTo(0,0);return;}if(typeof showScreen==="function")showScreen(howToReturnScreen);}
function howToFallbackImage(theme){return theme==="strength"?"./assets/strength-classic.jpg?v=13720":"./assets/engine-mountain-trail.jpg?v=13720";}
function renderHowToSlide(){const slide=howToSlides[howToIndex];applyHowToTarget(slide);const extras=slide.metrics?`<div class="guide-metric-grid">${slide.metrics.map(x=>`<div class="guide-metric"><span>${x[0]}</span><b>${x[1]}</b></div>`).join("")}</div>`:slide.feedback?`<div class="guide-feedback">${slide.feedback.map(x=>`<span>${x}</span>`).join("")}</div>`:slide.bullets?`<ul>${slide.bullets.map(x=>`<li>${x}</li>`).join("")}</ul>`:"";const tags=(slide.bullets||[]).slice(0,3).map(x=>x.replace(/^Use\s+/,"").replace(/^Bell Performance\s+/,"")).map(x=>`<i>${x.split(".")[0]}</i>`).join("");document.getElementById("howToTitle").textContent=slide.title;document.getElementById("howToSlide").innerHTML=`<div class="how-to-slide-copy"><div class="how-to-kicker">${slide.kicker}</div><h3>${slide.title}</h3><p>${slide.body}</p>${extras}</div><div class="how-to-visual" data-theme="${slide.theme||"system"}"><img src="${slide.image}" alt="" onerror="this.onerror=null;this.src='${howToFallbackImage(slide.theme)}';"><div class="how-to-visual-content"><div class="how-to-visual-badge">Bell Performance Tour</div><strong>${slide.visual}</strong><span>${slide.detail}</span>${tags?`<div class="how-to-tags">${tags}</div>`:""}</div></div>`;document.getElementById("howToProgress").style.width=`${((howToIndex+1)/howToSlides.length)*100}%`;document.getElementById("howToBack").disabled=howToIndex===0;document.getElementById("howToNext").textContent=howToIndex===howToSlides.length-1?"Finish Tour":"Next";document.getElementById("howToDots").innerHTML=howToSlides.map((_,i)=>`<button class="${i===howToIndex?"active":""}" aria-label="Go to slide ${i+1}" onclick="goToHowToSlide(${i})"></button>`).join("");}
function nextHowToSlide(){if(howToIndex>=howToSlides.length-1){closeHowToGuide();return;}howToIndex++;renderHowToSlide();}
function previousHowToSlide(){if(howToIndex>0){howToIndex--;renderHowToSlide();}}
function goToHowToSlide(i){howToIndex=i;renderHowToSlide();}
function toggleHowToAutoplay(){howToTimer?stopHowToAutoplay():startHowToAutoplay();}
function startHowToAutoplay(){document.getElementById("howToAutoPlay").textContent="Ⅱ Pause Auto-Advance";howToTimer=setInterval(()=>{if(howToIndex===howToSlides.length-1){stopHowToAutoplay();return;}howToIndex++;renderHowToSlide();},7200);}
function stopHowToAutoplay(){if(howToTimer)clearInterval(howToTimer);howToTimer=null;const button=document.getElementById("howToAutoPlay");if(button)button.textContent="▶ Auto-Advance";}
function hasSeenHowToGuide(){return localStorage.getItem(HOW_TO_KEY)==="1";}
function maybeShowHowToGuideAfterProfileSetup(){if(hasSeenHowToGuide())return;window.setTimeout(()=>openHowToGuide(0),350);}
window.addEventListener("keydown",event=>{if(document.getElementById("howToModal")?.classList.contains("hidden"))return;if(event.key==="Escape")closeHowToGuide();if(event.key==="ArrowRight")nextHowToSlide();if(event.key==="ArrowLeft")previousHowToSlide();});
