"use strict";

function localDateKey(date=new Date()){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;}
function localDateFromKey(key){const [y,m,d]=String(key||localDateKey()).split("-").map(Number);return new Date(y,m-1,d,12,0,0,0);}
function addLocalDays(key,delta){const d=localDateFromKey(key);d.setDate(d.getDate()+delta);return localDateKey(d);}
function mondayKeyFor(key=localDateKey()){const d=localDateFromKey(key),day=d.getDay(),offset=day===0?-6:1-day;d.setDate(d.getDate()+offset);return localDateKey(d);}
function selectedDashboardDateKey(){const today=localDateKey();data.dayNavigation=data.dayNavigation||{selectedDate:"",lastLocalDate:""};return data.dayNavigation.selectedDate||today;}
function setDashboardDate(key){data.dayNavigation.selectedDate=key;saveData();}
function navigateDashboardDay(delta){setDashboardDate(addLocalDays(selectedDashboardDateKey(),delta));}
function resetDashboardToToday(){setDashboardDate(localDateKey());}
function planDateKey(item){if(item?.scheduledDate)return item.scheduledDate;const days=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"],idx=days.indexOf(item?.day);return idx>=0?addLocalDays(mondayKeyFor(),idx):"";}
function stampCurrentPlanDates(){const monday=mondayKeyFor();const days=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"];(data.plan||[]).forEach((item,index)=>{const idx=Math.max(0,days.indexOf(item.day));item.scheduledDate=addLocalDays(monday,idx>=0?idx:index);item.sessionCompletions=item.sessionCompletions&&typeof item.sessionCompletions==="object"?item.sessionCompletions:{};});}
function renderDashboardDayNavigation(){const key=selectedDashboardDateKey(),today=localDateKey(),date=localDateFromKey(key),isToday=key===today;setText("missionDayHeading",isToday?"Today's Mission":`${new Intl.DateTimeFormat("en-US",{weekday:"long"}).format(date)} Mission`);setText("missionDayDate",new Intl.DateTimeFormat("en-US",{month:"long",day:"numeric",year:"numeric"}).format(date));const b=byId("dashboardDayButton");if(b){b.textContent=isToday?"Today":new Intl.DateTimeFormat("en-US",{weekday:"short",month:"short",day:"numeric"}).format(date);b.classList.toggle("viewing-today",isToday);b.title=isToday?"Viewing today":"Return to today";}document.querySelectorAll(".weekly-schedule-day").forEach(el=>el.classList.toggle("selected",el.dataset.date===key));}
function markPlannedSessionComplete(completed){let item=completed.planId?(data.plan||[]).find(x=>x.id===completed.planId):null;if(!item){const date=completed.scheduledDate||localDateKey(new Date(completed.completedAt));item=(data.plan||[]).find(x=>planDateKey(x)===date&&(x.mission===completed.name||x.secondaryMission===completed.name)&&!["skipped","replaced"].includes(x.status));}if(!item)return;item.sessionCompletions=item.sessionCompletions||{};let key=completed.planSessionKey;if(!key){const sessions=typeof sessionsFromPlanItem==="function"?sessionsFromPlanItem(item):[];key=sessions.find(x=>x.mission===completed.name&&!x.completed)?.sessionKey;}if(key)item.sessionCompletions[key]=completed.completedAt;const sessions=typeof sessionsFromPlanItem==="function"?sessionsFromPlanItem(item):[];const prescribed=sessions.filter(x=>!String(x.mission||"").startsWith("M-"));item.done=prescribed.length>0&&prescribed.every(x=>Boolean(item.sessionCompletions[x.sessionKey]));item.status=item.done?"completed":"planned";if(item.done)item.completedAt=completed.completedAt;}
function performLocalMidnightRollover(){const today=localDateKey();data.dayNavigation=data.dayNavigation||{};if(data.dayNavigation.lastLocalDate&&data.dayNavigation.lastLocalDate!==today){data.dayNavigation.selectedDate=today;data.settings.readiness.lastPromptDate="";}data.dayNavigation.lastLocalDate=today;if(!data.dayNavigation.selectedDate)data.dayNavigation.selectedDate=today;saveData({render:false});}
function scheduleMidnightRollover(){clearTimeout(window.__bellMidnightTimeout);const now=new Date(),next=new Date(now.getFullYear(),now.getMonth(),now.getDate()+1,0,0,1,0);window.__bellMidnightTimeout=setTimeout(()=>{performLocalMidnightRollover();renderApp();maybePromptDailyReadiness();scheduleMidnightRollover();},Math.max(1000,next-now));}

// Goal- and sex-aware accessory programming. Main lifts and engine prescriptions remain unchanged.
function coreProgrammingProfile(){const sex=data.settings?.sex||"Prefer not to say",goal=String(data.trainingBlock?.dualGoals?.strengthGoal||data.trainingBlock?.goalType||data.settings?.athleteMode||"Hybrid");return{sex,goal,bodybuilding:/bodybuilding|physique|hypertrophy|recomposition/i.test(goal),strength:/powerlifting|strength/i.test(goal),athlete:/athlete|functional|hybrid/i.test(goal)};}
function applyCoreProgrammingProfile(template){if(!template?.exercises)return template;const p=coreProgrammingProfile(),copy={...template,exercises:template.exercises.map(x=>({...x}))};copy.exercises=copy.exercises.map((ex,index)=>{if(index<2)return ex;let sets=Number(ex.sets)||0,name=String(ex.name||"");if(p.bodybuilding){if(p.sex==="Female"&&/Hip Thrust|Glute|Romanian Deadlift|Lunge|Hamstring|Row|Pulldown|Face Pull/i.test(name))sets=Math.min(5,sets+1);if(p.sex==="Male"&&/Lateral Raise|Curl|Pressdown|Chest|Incline|Row/i.test(name))sets=Math.min(5,sets+1);}else if(p.strength&&/Curl|Raise|Fly|Pressdown/i.test(name))sets=Math.max(2,sets-1);else if(p.athlete&&/Carry|Jump|Sprint|Single-Arm|Split Squat|Row/i.test(name))sets=Math.min(5,sets+1);return{...ex,sets,coreProfileNote:p.sex==="Prefer not to say"?`${p.goal} accessory profile`:`${p.goal} • ${p.sex} accessory profile`};});return copy;}
const bellBaseScaledTemplate=scaledTemplate;
scaledTemplate=function(name){return applyCoreProgrammingProfile(bellBaseScaledTemplate(name));};

const bellBaseBuildPlan=buildCurrentWeekPlan;
buildCurrentWeekPlan=function(){const result=bellBaseBuildPlan.apply(this,arguments);stampCurrentPlanDates();return result;};

const bellBaseWeeklyStrip=renderWeeklyScheduleStrip;
renderWeeklyScheduleStrip=function(){bellBaseWeeklyStrip();const monday=mondayKeyFor();document.querySelectorAll("#weeklyScheduleDays .weekly-schedule-day").forEach((el,index)=>{const key=addLocalDays(monday,index);el.dataset.date=key;el.onclick=()=>setDashboardDate(key);el.classList.toggle("today",key===localDateKey());});renderDashboardDayNavigation();};

document.addEventListener("DOMContentLoaded",()=>{normalizeData();performLocalMidnightRollover();if((data.plan||[]).some(item=>!item.scheduledDate))stampCurrentPlanDates();scheduleMidnightRollover();document.addEventListener("visibilitychange",()=>{if(!document.hidden){const before=data.dayNavigation?.lastLocalDate;performLocalMidnightRollover();if(before!==data.dayNavigation?.lastLocalDate)renderApp();}});});
